apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seonology-clock-page-tls
  namespace: seonology-apps
spec:
  secretName: seonology-clock-page-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - clock.seonology.com
