apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seonology-clock-page
  namespace: seonology-apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`clock.seonology.com`)
      kind: Rule
      services:
        - name: seonology-clock-page
          port: 80
      middlewares:
        - name: pass-tls-client-cert
          namespace: kube-system
        - name: cert-or-oidc-auth
          namespace: kube-system
  tls:
    secretName: seonology-clock-page-tls
    options:
      name: seonology-mtls
      namespace: kube-system
